USE [master]
GO

/****** Object:  Database [AspNetMvcECommerce]    Script Date: 03.07.2018 18:09:53 ******/
CREATE DATABASE [AspNetMvcECommerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AspNetMvcECommerce', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER1\MSSQL\DATA\AspNetMvcECommerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AspNetMvcECommerce_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER1\MSSQL\DATA\AspNetMvcECommerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AspNetMvcECommerce] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AspNetMvcECommerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AspNetMvcECommerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AspNetMvcECommerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AspNetMvcECommerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AspNetMvcECommerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AspNetMvcECommerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET RECOVERY FULL 
GO

ALTER DATABASE [AspNetMvcECommerce] SET  MULTI_USER 
GO

ALTER DATABASE [AspNetMvcECommerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AspNetMvcECommerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AspNetMvcECommerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AspNetMvcECommerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AspNetMvcECommerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AspNetMvcECommerce] SET QUERY_STORE = OFF
GO

USE [AspNetMvcECommerce]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AspNetMvcECommerce] SET  READ_WRITE 
GO

USE [AspNetMvcECommerce]
GO
/****** Object:  Table [dbo].[Article_details]    Script Date: 03.07.2018 18:13:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Article_details](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[article_id] [int] NULL,
	[color_id] [int] NULL,
	[size_id] [int] NULL,
	[brand_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Articles]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](25) NOT NULL,
	[description] [nvarchar](25) NOT NULL,
	[image_url] [nvarchar](225) NULL,
	[image_base64] [varchar](max) NULL,
	[category_id] [int] NULL,
	[price] [decimal](10, 2) NOT NULL,
	[quantity] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Brand]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Brand](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Colors]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Colors](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sizes]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sizes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 03.07.2018 18:13:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[login] [nvarchar](25) NOT NULL,
	[password] [nvarchar](225) NOT NULL,
	[role_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Roles] ON 
GO
INSERT [dbo].[Roles] ([id], [name]) VALUES (1, N'admin')
GO
INSERT [dbo].[Roles] ([id], [name]) VALUES (2, N'user')
GO
SET IDENTITY_INSERT [dbo].[Roles] OFF
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([id], [login], [password], [role_id]) VALUES (1, N'user1', N'1', 2)
GO
INSERT [dbo].[Users] ([id], [login], [password], [role_id]) VALUES (2, N'admin', N'123456', 1)
GO
INSERT [dbo].[Users] ([id], [login], [password], [role_id]) VALUES (3, N'u1', N'p1', 1)
GO
INSERT [dbo].[Users] ([id], [login], [password], [role_id]) VALUES (4, N'u1', N'p1', 1)
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
ALTER TABLE [dbo].[Article_details]  WITH CHECK ADD FOREIGN KEY([article_id])
REFERENCES [dbo].[Articles] ([id])
GO
ALTER TABLE [dbo].[Article_details]  WITH CHECK ADD FOREIGN KEY([brand_id])
REFERENCES [dbo].[Brand] ([id])
GO
ALTER TABLE [dbo].[Article_details]  WITH CHECK ADD FOREIGN KEY([color_id])
REFERENCES [dbo].[Colors] ([id])
GO
ALTER TABLE [dbo].[Article_details]  WITH CHECK ADD FOREIGN KEY([size_id])
REFERENCES [dbo].[Sizes] ([id])
GO
ALTER TABLE [dbo].[Articles]  WITH CHECK ADD FOREIGN KEY([category_id])
REFERENCES [dbo].[Categories] ([id])
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD FOREIGN KEY([role_id])
REFERENCES [dbo].[Roles] ([id])
GO

