//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVC_ECommerce_3.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_details
    {
        public int id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> color_id { get; set; }
        public Nullable<int> size_id { get; set; }
        public Nullable<int> brand_id { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Size Size { get; set; }
    }
}
